/*
 * Copyright (C) 2017 4th Line GmbH, Switzerland.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package smartHome;

import java.awt.event.ItemEvent;

/**
 *
 * @author Han
 */
public class TelevisionGUI extends javax.swing.JFrame {

    /**
     * Creates new form TelevisionGUI
     */ 
        
    public TelevisionGUI(){
        initComponents();
        setVisible(true);
        setSize(640,360);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PowerButton = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        VolumeSlider = new javax.swing.JSlider();
        VolumeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo TV");
        setMinimumSize(new java.awt.Dimension(450, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 300));
        getContentPane().setLayout(null);

        PowerButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                itemStateChanged(evt);
            }
        });
        getContentPane().add(PowerButton);
        PowerButton.setBounds(540, 280, 98, 40);

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(310, 20, 50, 230);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/off.jpg")));
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 360);
        jLabel1.setLayout(null);
        
        VolumeSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        VolumeSlider.setName("VolumeSlider"); // NOI18N
        jLabel1.add(VolumeSlider);
        VolumeSlider.setBounds(190, 70, 51, 200);

        VolumeLabel.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        VolumeLabel.setForeground(new java.awt.Color(59, 255, 0));
        VolumeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VolumeLabel.setText("70");
        jLabel1.add(VolumeLabel);
        VolumeLabel.setBounds(190, 275, 51, 20);
        

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_itemStateChanged
        // TODO add your handling code here:
        if(PowerButton.isSelected() == false) jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/off.jpg")));
        else jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_1maxresdefault.jpg")));
        jLabel1.repaint();
        VolumeLabel.repaint();
        VolumeSlider.repaint();
    }//GEN-LAST:event_itemStateChanged
    public javax.swing.JToggleButton getPowerButton(){
        return PowerButton;
    }
    public javax.swing.JSlider getVolumeSlider(){
        return VolumeSlider;
    }
    public javax.swing.JLabel getVolumeLabel(){
        return VolumeLabel;
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelevisionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelevisionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelevisionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelevisionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new TelevisionGUI();
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton PowerButton;
    private javax.swing.JLabel VolumeLabel;
    private javax.swing.JSlider VolumeSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
